name: Desplegar en desarrollo

on:
  push:  
    branches: [dev]

jobs:
  CI-CD:
    runs-on: vps
    steps:
      - run: echo "🐧 El job esta corriendo en ${{ runner.os }}!"
      - name: Clonar reporsitorio
        uses: actions/checkout@v4
      - run: docker build -t api_gestion_dominios_dev:latest -t api_gestion_dominios_dev:$(date +%F_%H-%M-%S)  .
      - run: cd ~/DockerCompose_SistemaDominios && docker stop api_dominio_dev && docker remove api_dominio_dev && docker-compose -f docker-compose-dev.yml up -d api_dominio_dev